# Site settings
title: Freifunk München
email: 
description: "Die nichtkommerzielle Initiative für den Aufbau freier (Funk-)Netzwerke in München"
baseurl: ""
url: "https://ffmuc.net/"
twitter_username: FreifunkMUC
github_username:  FreifunkMUC
mastodon_username: "@freifunkMUC"
mastodon_link: "https://social.ffmuc.net/""

gems:
  - jekyll-feed
  - jekyll-seo-tag
favicon: assets/favicon/favicon.ico
# Build settings
markdown: kramdown
permalink: pretty

# Custom headers
webrick:
  headers:
      Content-Security-Policy: default-src 'none'; script-src 'unsafe-eval' 'unsafe-inline' 'self'  ; connect-src 'self' firmware.ffmuc.net; img-src 'self' cdn.rawgit.com raw.githubusercontent.com ; style-src 'self' 'unsafe-inline' 'unsafe-eval' ;    media-src 'self' ; font-src 'self'; frame-src 'self';
